Update job 3

diff --git a/.github/workflows/assignment3.yml b/.github/workflows/assignment3.yml
--- a/.github/workflows/assignment3.yml
+++ b/.github/workflows/assignment3.yml
@@ -175,3 +175,23 @@ jobs:
           curl --location --request POST 'http://127.0.0.1:5001/books' -H "Content-Type: application/json" -d '{"title": "The Adventures of Tom Sawyer", "ISBN": "9780195810400", "genre": "Fiction"}'
           curl --location --request POST 'http://127.0.0.1:5001/books' -H "Content-Type: application/json" -d '{"title": "I, Robot", "ISBN": "9780553294385", "genre": "Science Fiction"}'
           curl --location --request POST 'http://127.0.0.1:5001/books' -H "Content-Type: application/json" -d '{"title": "Second Foundation", "ISBN": "9780553293364", "genre": "Science Fiction"}'
+
+      - name: Reading and executing query.txt queries
+        run: |
+          if [ ! -f "query.txt" ]; then
+            echo "File not found!" >> response.txt
+            exit 1
+          fi
+          while IFS= read -r line
+          do
+            echo "query: $line" >> response.txt
+            url="http://127.0.0.1:5001/books$line"
+            res=$(curl --location --request GET '$url')
+            echo "response: $res" >> response.txt
+          done < "query.txt"
+      
+      - name: Upload response.txt file
+        uses: actions/upload-artifact@v4
+        with:
+          name: queries-response
+          path: response.txt
